const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  SET_USER_CART : "SET_USER_CART",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART : 'CLEAR_CART',
  GET_CART_FROM_FIREBASE: 'GET_CART_FROM_FIREBASE',
  SET_CART_ITEMS :'SET_CART_ITEMS',
  SAVE_CART_ITEMS : 'SAVE_CART_ITEMS'
};
export default CartActionTypes;
